### ISSUE TITLE
Wyvernhaven house broken

### ISSUE THREAD

**Issue by Vailyn** [GreatOrator/TolkienCraftII#83] opened 2016-05-01 10:29 UTC
I purchased the house in wyvernhaven at X: 419, Z: 1520, and upon using the key, when it built, the protected area directly behind the house demolished the entire northwest corner of the house. Minor bug overall in a great pack, but still a nuisance.

**Comment by GreatOrator** [comment] 2016-05-01 11:06
Interesting...will take a look at that...thank you for reporting that, I agree, nuisance and will have to move the antibuilder to avoid that.  Could you post a pic so I can get an idea of where the total area affected is?

**Comment by Vailyn** [comment] 2016-05-01 11:35
Here's a Few. I'm assuming it's because the house runs into the wall if it were to finish building.
It's not a huge deal on my server since I run it for just my wife, brother and myself. But there's something fun about having a quaint village home away from massive base.

https://www.dropbox.com/s/83tflejo0m7vlvh/Screenshot%202016-05-01%2004.30.47.png?dl=0

https://www.dropbox.com/s/oafju3zce5cdcd2/Screenshot%202016-05-01%2004.30.59.png?dl=0

https://www.dropbox.com/s/t3m6wtj0uxri7bd/Screenshot%202016-05-01%2004.31.06.png?dl=0

https://www.dropbox.com/s/w26jfbiihkhrweb/Screenshot%202016-05-01%2004.31.17.png?dl=0

**Comment by GreatOrator** [comment] 2016-05-01 11:42
Hmmm, I think I will need to rework that house.  I could have sworn it fit in the area back when I implemented them but looks like it does not fit within the white square that it was intended for

**Comment by Vailyn** [comment] 2016-05-01 11:48
If it moved forward two blocks and the antibuilder moved back 2 blocks perhaps that could work? Just first thought from looking at it. Thanks for the quick reply, and for the amazing pack.

**Comment by GreatOrator** [comment] 2016-05-01 12:37
Thank you for the compliments, and yeah, already got it figured out.  Think I am going to switch from using the tolkientweaks version to the townbuilder version since that was what that mod was created for anyways.  It was born from the function in tolkien tweaks and makes it easier for me to fix this issue.  Will try to get an update out this week for sure...besides, bunch of mods have updated as well

**Comment by Vailyn** [comment] 2016-05-01 19:35
Awesome. I'm surprised no one else caught that before me. First bug report I've submitted since I can usually find answers to everything else (usually me doing something dumb). I'll be watching for an update. Thanks again!

**Comment by GreatOrator** [comment] 2016-05-01 20:16
Will work on getting a map update out within the next few days to fix/address this.  Will also require a modpack update as well to coincide with the map changes needed.

Will leave this open to remind myself in the meantime and thank you for finding the bug!

**Comment by GreatOrator** [comment] 2016-05-03 01:23
Should be fixed in the new update available shortly

**Closed by GreatOrator** 2016-05-03 01:23 UTC
Labels: bug
