### ISSUE TITLE
Server crash - when clicking on the ground with a master staff while away from minons

### ISSUE THREAD

**Issue by ProsperCraft** [GreatOrator/TolkienCraftII#100] opened 2016-06-19 18:04 UTC
When I am not near my minons and click on the ground with my master staff it crashes the server

I have done this about 6 times.
- TolkienCraft II version: 2.9.2
## Crash report

```
http://pastebin.com/SL6GYFi8
http://pastebin.com/Ds7VZLAR
```

**Comment by GreatOrator** [comment] 2016-06-19 18:26
Will report to atomic stryker, but I fear he is no longer updating the 1.7.10 version

**Comment by GreatOrator** [comment] 2016-06-21 14:44
Odd thing about those crash logs, each one has different information as part of the crash even though the cause is the same...

**Comment by GreatOrator** [comment] 2016-09-08 20:47
Has this been fixed in 2.9.5?

**Closed** 2017-03-10 17:13 UTC
Labels: bug
