### ISSUE TITLE
Naturally Spawning Rohirric Crafting Tables

### ISSUE THREAD

**Issue by KremeChoco** [GreatOrator/TolkienCraftII#89] opened 2016-05-22 08:34 UTC
There seems to be an issue with worldgen. 
Seems some LOTR crafting tables are genning naturally.

At first I thought it was the Draconis map.
I ran a new world without Draconis. Same issue.
You can check the coords in a Draconis world using the same on the image below

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 1566
* TolkienCraft II version: 2.8.10

https://imgur.com/a/ySYWN

**Comment by GreatOrator** [comment] 2016-05-22 10:26
yeah, turns out that it is possibly because of using the level.dat from the extended content downloads.  that level.dat was only used as a placeholder to upload to curse (at least from the few other reports).  try replacing the level.dat from the latest default map download and see what happens.

**Comment by GreatOrator** [comment] 2016-05-22 10:52
ALright, so dug a little deeper, only seems to happen where rivers generate, so at least figured out that much, but why and why all of the sudden...

**Comment by GreatOrator** [comment] 2016-05-22 22:27
So good news is....figured out why it happens, to an extent.  The bad news is, unless I can find a way to create a small mod to patch bad code...not going to be able to fix it.  The issue can be best described here:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287390-the-lord-of-the-rings-mod-bringing-middle-earth-to?comment=6085

but knowing how mevans is, probably won't get fixed as it's going to be said it's not his fault, and the mod that is also involved as far as tolkiencraft is concerned, chococraft, does not seem to be active any longer as well and removing it from the pack at this stage literally renders the map unusable due to the crashes.

It does appear to be isolated to rivers and plains however.

So will try the patch method, but closing as won't fix as this may be one bug there is nothing that can be done about it. (It has been reported either way to both devs)

**Closed by GreatOrator** 2016-05-22 22:27 UTC
Labels: bug

**Comment by tevrenos** [comment] 2016-06-19 11:17
Did you get to find a solution for this yet?? I also am having the issue..

ps:great creations have been enjoying a little too much:P

**Comment by GreatOrator** [comment] 2016-06-19 12:37
Unfortunately no, the dev for the LotR mod has been unresponsive regarding the issue and telling 8-12 other mod devs to "fix" their mods is unreasonable.  Still trying though, so have faith :D just consider it early game fuel

**Comment by tevrenos** [comment] 2016-06-19 12:55
eheh.. thanks a lot for the quick answer, please let us know how if you manage to fix it. i am sure you will solve it one way or another. also, please keep up the great work :D

**Comment by GreatOrator** [comment] 2016-06-19 13:48
Absolutely, and be sure that if I do get it fixed I will be shouting from the mountain tops :D

**Comment by Magikmaliki0976** [comment] 2017-09-02 19:41
hey guys so i have a way to fix this problem. if you are still interested in playing this mod pack but hate the problem of the tables generating everywhere then here is the simple fix i used. when you start a server or single player you can go in to the server file or single player file and you have the server properties file to change stuff. in the properties you have a setting called level type. change default to BIOMESOP as that mod is in the pack. also delete the world folder if you have previously loaded a world. then restart and it should world gen according to biomes o' plenty. you may miss out on some biomes but so far we havent seen that problem again.

**Comment by GreatOrator** [comment] 2017-09-03 13:31
Actually, this reminds me, Mevans finally pinpointed the cause and one of the updates fixes it.  I just have to see if I can update TC2 without breaking everything to fix this.
